{
// no shift
  {
  // no shift, no alt
    {
      [KBD_CARET] = '^',
      [KBD_TAB] = '\t',
      [KBD_LESS] = '<',
      [KBD_SPACE] = ' ',
      [KBD_BACK] = 127,
      [KBD_ENTER] = '\n',

      [KBD_PUNCT_1_1] = 'ß',
      [KBD_PUNCT_1_2] = '´',
      [KBD_PUNCT_2_1] = 'ü',
      [KBD_PUNCT_2_2] = '+',
      [KBD_PUNCT_2_3] = '#',
      [KBD_PUNCT_3_1] = 'ö',
      [KBD_PUNCT_3_2] = 'ä',
      [KBD_PUNCT_4_1] = ',',
      [KBD_PUNCT_4_2] = '.',
      [KBD_PUNCT_4_3] = '-',

      [KBD_A] = 'a',
      [KBD_B] = 'b',
      [KBD_C] = 'c',
      [KBD_D] = 'd',
      [KBD_E] = 'e',
      [KBD_F] = 'f',
      [KBD_G] = 'g',
      [KBD_H] = 'h',
      [KBD_I] = 'i',
      [KBD_J] = 'j',
      [KBD_K] = 'k',
      [KBD_L] = 'l',
      [KBD_M] = 'm',
      [KBD_N] = 'n',
      [KBD_O] = 'o',
      [KBD_P] = 'p',
      [KBD_Q] = 'q',
      [KBD_R] = 'r',
      [KBD_S] = 's',
      [KBD_T] = 't',
      [KBD_U] = 'u',
      [KBD_V] = 'v',
      [KBD_W] = 'w',
      [KBD_X] = 'x',
      [KBD_Y] = 'y',
      [KBD_Z] = 'z',

      [KBD_0] = '0',
      [KBD_1] = '1',
      [KBD_2] = '2',
      [KBD_3] = '3',
      [KBD_4] = '4',
      [KBD_5] = '5',
      [KBD_6] = '6',
      [KBD_7] = '7',
      [KBD_8] = '8',
      [KBD_9] = '9',

      [KBD_NUM_0] = '0',
      [KBD_NUM_1] = '1',
      [KBD_NUM_2] = '2',
      [KBD_NUM_3] = '3',
      [KBD_NUM_4] = '4',
      [KBD_NUM_5] = '5',
      [KBD_NUM_6] = '6',
      [KBD_NUM_7] = '7',
      [KBD_NUM_8] = '8',
      [KBD_NUM_9] = '9',

      [KBD_NUM_TIMES] = '*',
      [KBD_NUM_PLUS] = '+',
      [KBD_NUM_MINUS] = '-',
      [KBD_NUM_PUNCT] = ',',
    },

    // shift, no alt
    {
      [KBD_CARET] = '°',
      [KBD_TAB] = '\t',
      [KBD_LESS] = '<',
      [KBD_SPACE] = ' ',
      [KBD_BACK] = 127,
      [KBD_ENTER] = '\n',

      [KBD_PUNCT_1_1] = '?',
      [KBD_PUNCT_1_2] = '`',
      [KBD_PUNCT_2_1] = 'Ü',
      [KBD_PUNCT_2_2] = '*',
      [KBD_PUNCT_2_3] = '\'',
      [KBD_PUNCT_3_1] = 'Ö',
      [KBD_PUNCT_3_2] = 'Ä',
      [KBD_PUNCT_4_1] = ';',
      [KBD_PUNCT_4_2] = ':',
      [KBD_PUNCT_4_3] = '_',

      [KBD_A] = 'A',
      [KBD_B] = 'B',
      [KBD_C] = 'C',
      [KBD_D] = 'D',
      [KBD_E] = 'E',
      [KBD_F] = 'F',
      [KBD_G] = 'G',
      [KBD_H] = 'H',
      [KBD_I] = 'I',
      [KBD_J] = 'J',
      [KBD_K] = 'K',
      [KBD_L] = 'L',
      [KBD_M] = 'M',
      [KBD_N] = 'N',
      [KBD_O] = 'O',
      [KBD_P] = 'P',
      [KBD_Q] = 'Q',
      [KBD_R] = 'R',
      [KBD_S] = 'S',
      [KBD_T] = 'T',
      [KBD_U] = 'U',
      [KBD_V] = 'V',
      [KBD_W] = 'W',
      [KBD_X] = 'X',
      [KBD_Y] = 'Y',
      [KBD_Z] = 'Z',

      [KBD_0] = '=',
      [KBD_1] = '!',
      [KBD_2] = '"',
      [KBD_3] = '§',
      [KBD_4] = '$',
      [KBD_5] = '%',
      [KBD_6] = '&',
      [KBD_7] = '/',
      [KBD_8] = '(',
      [KBD_9] = ')',
    },
  },

// shift
  {
  // no shift, alt
    {
    },

  // shift, alt
    {
    },
  },
}
