C_SRC := \
    _exit.c \
    _fini.c \
    _init.c \
    close.c \
    execve.c \
    fcntl.c \
    fork.c \
    fstat.c \
    getpid.c \
    gettimeofday.c \
    isatty.c \
    kill.c \
    link.c \
    lseek.c \
    mkdir.c \
    open.c \
    read.c \
    sbrk.c \
    sigprocmask.c \
    stat.c \
    times.c \
    unlink.c \
    wait.c \
    write.c

include ../Makefile.folders

CFLAGS += -D_COMPILING_NEWLIB
